# -*- coding: utf-8 -*-
"""bdt-sentiment.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqVkPejFuqdC-589G8HbBed2-6u3Kggv
"""

!pip install transformers

import torch
import pandas as pd
from transformers import pipeline
from sklearn.metrics import accuracy_score
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/Datasets/tweets-sentiment-synth.csv'

data = pd.read_csv(file_path, sep=',')

sample_tweets = data['tweet'].tolist()

pipe = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest")

results = pipe(sample_tweets)

predicted_labels = [result['label'] for result in results]

true_labels = data['sentiment'].tolist()

accuracy = accuracy_score(true_labels, predicted_labels)

print(f"Accuracy: {accuracy}")

import torch
import pandas as pd
from transformers import pipeline
from sklearn.metrics import accuracy_score
from google.colab import auth
from google.cloud import storage
from io import StringIO

auth.authenticate_user()

gcs_bucket_name = 'datasets-twitter'
gcs_file_path = 'tweets-sentiment-synth.csv'

storage_client = storage.Client()

bucket = storage_client.get_bucket(gcs_bucket_name)
blob = bucket.blob(gcs_file_path)

csv_file = blob.download_as_text()
data = pd.read_csv(StringIO(csv_file))

sample_tweets = data['tweet'].tolist()

pipe = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest")

results = pipe(sample_tweets)

predicted_labels = [result['label'] for result in results]

true_labels = data['sentiment'].tolist()

accuracy = accuracy_score(true_labels, predicted_labels)

print(f"Accuracy: {accuracy}")